version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./var/static:/srv/FDM/var/static
      - ./var/media:/srv/FDM/var/media
      - ./logs:/srv/FDM/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./tmp:/tmp
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    restart: always
    build: .
    volumes:
      - .:/srv/FDM
      - ../fdm-fe:/srv/FDM/angular
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      bash -c "python manage.py migrate
      && python manage.py collectstatic --no-input
      && gunicorn -c gunicorn.py fdm.wsgi"

volumes:
  db_data:
